config/routes.rb
CarrierwaveMultiFileUpload::Application.routes.draw do
    root :to            => 'pages#home'

    resources :galleries do
      resources :photos, :except => [:update, :edit]
    end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name
  has_many :photos, :dependent => :destroy 
  validates_presence_of :name
  validates_uniqueness_of :name

  def at_least_one_photo?
    self.photos.present?
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :photo_file, :gallery_id
  belongs_to :gallery
  
  mount_uploader :photo_file, PhotoFileUploader
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end


  def show
    @gallery = Gallery.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end


  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end


  def edit
    @gallery = Gallery.find(params[:id])
  end


  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to galleries_url, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to galleries_url , notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    
  before_filter :the_gallery
  
  def index
    @photos = Photo.where("gallery_id = ?", the_gallery)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end


  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end


  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end


  def create
    @photo = @gallery.photos.new(params[:photo])
    if @photo.save

    else
      render :json => { "errors" => @photo.errors } 
    end
  end


  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to gallery_photos_path(@gallery) }
      format.json { head :no_content }
    end
  end
end


private 

def the_gallery
  @gallery = Gallery.find(params["gallery_id"])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
    
  def no_gallery?
      !Gallery.first
  end
   
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	</br>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
	</br>
  <button class="btn primary" type="submit"> Save</button>
	<%= link_to 'Back', galleries_path %>
<% end %>

app/views/galleries/_galleries_navigation.erb
<ul>
	<li><%= link_to "Home", 	:controller => "pages", :action => "home" %></li>
</ul>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form' %>

app/views/galleries/index.html.erb
<h1>Galleries</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<br>
<% @galleries.each do |gallery| %>
  <tr>
    <td><strong><%= link_to gallery.name, gallery_path(gallery.id) %><strong></td>
    <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
    <td><%= link_to 'Destroy', gallery, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

</br>

<%= link_to 'Add a New Gallery', new_gallery_path %>
 
<% if no_gallery? then %>
	<section>
		</br>
		<p>This is the Index page for Gallery. There are no Galleries at the moment. Click 'Add a New Gallery' to add one. Once you add a gallery or two, click on the gallery name to navigate to the Gallery/Show action. From there you may navigate to the Photo Upload feature.<p>
	</section>
<% else %>
	<section>
		</br>
		<p>Click on a Gallery Name to view/upload photos.<p>
	</section>
<% end %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>
<p>
<h1>Gallery Name:	<%= @gallery.name %></h1>
	<br>
</p>

<p>This is the Gallery (Show) page. There's not really much here to show because we have a very slim Gallery model. Gallery name is pretty much it. <p>

</br>
<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %> |
<% if @gallery.at_least_one_photo? %> 
	<%= link_to 'Photos', gallery_photos_path(@gallery) %>  |
<% end %>
<%= link_to 'Upload Photos', new_gallery_photo_path(@gallery) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
  <title>MultiFileUpload</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>		
	
		<div class="col-width">		
			<hgroup id="logo">
				<h1 id="site-title">
					<a rel="home" title="Multiple File Upload with Carrierwave and Jquery-File-Upload"
					href="http://localhost:3000//">Carrierwave/Jquery-File-Upload</a>
				</h1>
				
			</hgroup>			
			<nav id="navigation">
				<div class="menu">
					<%= render "#{controller_name}" + "_navigation" %>			
				</div>
 			</nav>
		</div>
	
	 			   
				<%= yield %>
		
	</div>
	
</body>
</html>

app/views/pages/_pages_navigation.html.erb
<ul>
	<li><%= link_to "Home", 	:controller => "pages", :action => "home" %></li>
	<li><%= link_to "Galleries", :controller => "galleries", :action => "index" %></li>
</ul>

app/views/pages/home.erb
<h2> Sample  Multiple File Upload<h2>
</br>



</br>
<h4> To see how this demo app works, you must first add a Gallery. So let's go to the
	<%=link_to "Gallery Page", galleries_path %>.</h4>

app/views/photos/_photos_navigation.erb
<ul>
	<li><%= link_to "Home", 	:controller => "pages", :action => "home" %></li>
	<li><%= link_to "Galleries", :controller => "galleries", :action => "index" %></li>
</ul>

app/views/photos/index.html.erb
<h1>Gallery Photos:	<%= @gallery.name %></h1>
<br />

<p>This is Photos (Index Action) page. To view/edit a photo, hover over and click on the thumbnail.<p>

<br />
<%= link_to 'Back', gallery_path(@gallery) %> |
<%= link_to 'Upload Photos', new_gallery_photo_path(@gallery) %>
<br />
<div id="gallery">
  <ul id="grid">
    <% @photos.each do |pic| %>
     <li><%= link_to image_tag(pic.photo_file.url(:thumb).to_s), gallery_photo_path(@gallery,pic) %></li>
    <% end %>
  </ul>
</div>

    

app/views/photos/new.html.erb
<!-- The form_for...remote=>true ensures that the csrf meta tag is carried thru to save
the authenticity token. Without this, authentication gets dropped with an ajax call and
strange things happen, lost authenticity + possible fall thru logic to next GET action. 
Also see the setting in development.rb environment. New as of 3.2.3 -->

<%= form_for [@gallery, @photo], :remote => true do %>

	<h1>Upload Gallery Photos:	<%= @gallery.name %></h1>
	<br>
	<p>For multiple file uploading, I used the simplest version of the Jquery-File-Upload plugin. There are no bells and whistles here. First, you'll want to browse and select your file(s), Then, after clicking "Open"...BAM! The files are uploaded. There is no submit key here (yet). Right now, it's just the  basics, folks. Also, since this is a dev app, your uploaded photo files will go in the Public folder. In real life, you'd probably store them somewhere else, perhaps using Amazon's S3 cloud file storage service.<p>
	<br>
	<p id="notice"><%= notice %></p>

		Upload Photos: 
		<input id="fileupload" type="file" name="photo[photo_file]" multiple>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script src="/jquery-file-upload/vendor/jquery.ui.widget.js"></script>
		<script src="/jquery-file-upload/jquery.iframe-transport.js"></script>
		<script src="/jquery-file-upload/jquery.fileupload.js"></script>
		<script>
		$(function () {
		    $('#fileupload').fileupload({
		        dataType: 'json',
		        url: '<%= gallery_photos_path(@gallery.id) %>',
		        done: function (e, data) {
		            $.each(data.result, function (index, file) { 
		               $('<li><img src="'+file.thumbnail_url+'"></li>').appendTo('#thumbs');
		            });
		        }
		    });
		});
		</script>

		</br>
		<%= link_to 'Back', galleries_path %> |
		<%= link_to 'Photos Viewer', gallery_photos_path(@gallery) %>
		</br>
	
		<ul id="thumbs" class="cf">
	<!-- json-ajax response here, see fileupload script above, .appendTo css id:"thumbs"-->
		</ul>
<% end %>

app/views/photos/show.html.erb
<h1>Gallery:	<%= @gallery.name %>, Photo: <%= @photo.photo_file %></h1>
</br>
<p>This is the Photos (Show) page. The path and file name are included in the title. In this example, the photo display size is preset: I set the "medium" version of photos to a height of 540 pixels in photo_file_uploader.rb. It makes for an easier demo. There are many other options available, including dynamic resizing. <p>
<br>
<p id="notice"><%= notice %></p>

<%= link_to image_tag(@photo.photo_file.url(:medium).to_s), gallery_photo_path(@gallery,@photo) %>
</br>
<%= link_to "Delete Photo", gallery_photo_path(@gallery, @photo), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %> |
<%= link_to 'Back', gallery_photos_path %>